name: Build and deploy to github pages

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    name: Build and deploy main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.25.0
      - name: setup node version
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install and build
        run: |
          npm install
          npm run build -- --base=/${{github.event.repository.name}}/

      - name: Deploy to gh pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist

      - name: Upload build files as artifacts
        uses: actions/upload-aritifact@v3
        with:
          name: published
          path: dist